### ISSUE TITLE
Where your z0?

### ISSUE THREAD

**Issue by Juddd** [tobydriscoll/sc-toolbox#20]
I can find all parameters in your result of `diskmap` and `hplmap`:

![image](https://github.com/tobydriscoll/sc-toolbox/assets/10048069/24882d46-10e7-4333-9e43-41108fd030cc)

But why no z_0? This is your formula:

![image](https://github.com/tobydriscoll/sc-toolbox/assets/10048069/82889b4f-a567-4e53-9046-750b579d746b)

I can't build the whole map correctly without the value of z_0

**Comment by Juddd** [comment]
@tobydriscoll It's amazing that you didn't introduce how to get this f(z0) in your [guide.pdf](https://tobydriscoll.net/project/sc-toolbox/guide.pdf). I could not find it on the Internet, and there were no issues raised. It seemed that I was the only person in the world who didn't know, and everyone else knew about it by default. :)

**Comment by tobydriscoll** [comment]
The mapping implementation always chooses the nearest prevertex as the starting point for integration, so there is no single value of z0 to refer to.

The inverse of the map is not itself an SC map, so there is no meaningful multiplicative constant defined for the inverse map. Instead, it simply shows you what it is the inverse of.
